server:
  port: 8801
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zk@19940206
    url: jdbc:mysql://47.93.218.163:3306/save?useUnicode=true&characterEncoding=utf8
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  application:
    name: cloud-save
  cloud:
    nacos:
      discovery:
        server-addr: 47.93.218.163:8848
        namespace: 2775e7fc-2543-4d8d-ab69-19bd18478a74
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
